# site settings
title: EDP
subtitle: Ecosystems of Deep Plasticity
email: youremailaddress@gmail.com
description: We are not looking for a knight when many are already galloping in the right direction.<br /> We are the bridge between the ivory tower and professionals helping communities around the globe.<br /> We position ourselves in the gap, the décalage, between the deep well of social and behavioral scientific knowledge and those looking to meaningfully reflect on their efforts to do right by the communities they so passionately serve.
baseurl: "/forty-jekyll-theme" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown

sass:
  style: compressed
