# site settings
title: EDP
subtitle: Ecosystems of Deep Plasticity
email: ouremail@edp.eu
description: We are not looking for a knight when many are already galloping in the right direction.<br /> We are the bridge between the ivory tower and professionals helping communities around the globe.<br /> We position ourselves in the gap, the décalage, between the deep well of social and behavioral scientific knowledge and those looking to meaningfully reflect on their efforts to do right by the communities they so passionately serve.
baseurl: "/edp" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author:
street_address: Placeholder Rd
city: Brussels
zip_code: 000000
country: Belgium
phone: 000 0000-00000

# homepage tiles
tiles-source: pages # accepts "posts" or "pages" "landpages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed

#Collections
collections:
  tooltips:
    output: false
